[general]
fps_counter = false
judge_offset = 0
autoplay = false

[paths]
tja_path = 'Songs'
video_path = 'Videos'

[keybinds]
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[audio]
#Options: ASIO, Windows WASAPI
device_type = 'Windows WASAPI'
buffer_size = 6

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
vsync = true
