[general]
fps_counter = false
judge_offset = 0
visual_offset = 0
language = "ja"
hard_judge = 108

[nameplate]
name = 'どんちゃん'
title = 'ドンだーデビュー！'
dan = -1
gold = false

[paths]
tja_path = ['Songs']
video_path = 'Videos'

[keys]
exit_key = 'A'
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[gamepad]
left_kat = [10]
left_don = [16]
right_don = [17]
right_kat = [12]

[audio]
device_type = "ALSA"
buffer_size = 64
sample_rate = -1
exclusive = false

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
target_fps = -1
vsync = true
