[general]
fps_counter = false
judge_offset = 0
autoplay = true

[paths]
tja_path = 'Songs'
video_path = 'Videos'

[keybinds]
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[audio]
device_type = 'WASAPI'
asio_buffer = 6

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
vsync = true
